# Generated by Django 3.2.15 on 2022-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_organizer', '0002_alter_entries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=30, unique=True), max_length=200, unique=True),
        ),
    ]
