# Generated by Django 3.2.15 on 2022-08-10 10:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_organizer', '0005_alter_entries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
