# Generated by Django 3.2.15 on 2022-08-10 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts_organizer', '0006_alter_entries_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='user',
        ),
        migrations.AddField(
            model_name='categories',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
