# Generated by Django 3.2.15 on 2022-08-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_organizer', '0007_auto_20220810_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='user',
        ),
    ]
