# Generated by Django 3.2.15 on 2022-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_organizer', '0009_categories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
