# Generated by Django 3.2.15 on 2022-08-15 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts_organizer', '0011_entries_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('name', 'slug', 'user')},
        ),
    ]
