# Generated by Django 3.2.15 on 2022-08-23 17:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_organizer', '0018_auto_20220820_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='image',
            field=cloudinary.models.CloudinaryField(default='no_image', max_length=255, verbose_name='image'),
        ),
    ]
