# Generated by Django 3.2.15 on 2022-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_apporoved_comments_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='process',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
