# Generated by Django 3.2.15 on 2022-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
